[package]
name = "search"
version = "0.1.0"
edition = "2021"

[dependencies]
qdrant-client = "1.12.1"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.132"
tantivy = "0.22.0"

database = { path = "../database" }
